In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn=sql.connect("chinook.db")
conn

In [3]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [4]:
pd.read_sql_query("select * from sqlite_master",con=conn) # here we have index and table both

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,index,sqlite_autoindex_playlist_track_1,playlist_track,12,None
11,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
12,index,ifk_albumartist_id,album,16,CREATE INDEX [ifk_albumartist_id] ON [album] (...
13,index,ifk_customersupport_rep_id,customer,17,CREATE INDEX [ifk_customersupport_rep_id] ON [...
14,index,ifk_employeereports_to,employee,18,CREATE INDEX [ifk_employeereports_to] ON [empl...
15,index,ifk_invoicecustomer_id,invoice,19,CREATE INDEX [ifk_invoicecustomer_id] ON [invo...
16,index,ifk_invoice_lineinvoice_id,invoice_line,20,CREATE INDEX [ifk_invoice_lineinvoice_id] ON [...
17,index,ifk_invoice_linetrack_id,invoice_line,21,CREATE INDEX [ifk_invoice_linetrack_id] ON [in...
18,index,ifk_playlist_tracktrack_id,playlist_track,22,CREATE INDEX [ifk_playlist_tracktrack_id] ON [...
19,index,ifk_trackalbum_id,track,23,CREATE INDEX [ifk_trackalbum_id] ON [track] ([...
20,index,ifk_trackgenre_id,track,24,CREATE INDEX [ifk_trackgenre_id] ON [track] ([...
21,index,ifk_trackmedia_type_id,track,25,CREATE INDEX [ifk_trackmedia_type_id] ON [trac...
22,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
23,index,sqlite_autoindex_wishlist_track_1,wishlist_track,262,None
24,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
25,view,CUSTOMER_ABV2_90,CUSTOMER_ABV2_90,0,CREATE VIEW CUSTOMER_ABV2_90 as \n sele...
26,view,customer_get_90_dollars,customer_get_90_dollars,0,CREATE VIEW customer_get_90_dollars as\n Sel...
27,view,customer_usa,customer_usa,0,CREATE VIEW customer_usa as\n sele...
28,view,customer_gt_90_dollars,customer_gt_90_dollars,0,CREATE VIEW customer_gt_90_dollars as\n Sele...
29,view,city_redmond,city_redmond,0,CREATE VIEW city_redmond as\n sele...
30,view,CUSTOMER_ABV3_80,CUSTOMER_ABV3_80,0,CREATE VIEW CUSTOMER_ABV3_80 as \n sele...

In [5]:
sql_query("select * from sqlite_master where type='table'") # taking out table only

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
11,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
12,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."

<img src="chinook.jpeg" width ="60%">
# to render image (double on image to see html code )

In [6]:
# select all from invoice table
query='''
select * from invoice
'''
sql_query(query)

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total,tax,subtotal
0,1,18,2017-01-03 00:00:00,627 Broadway,New York,NY,USA,10012-2612,15.84,0,15.84
1,2,30,2017-01-03 00:00:00,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,9.90,0,9.90
2,3,40,2017-01-05 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,1.98,0,1.98
3,4,18,2017-01-06 00:00:00,627 Broadway,New York,NY,USA,10012-2612,7.92,0,7.92
4,5,27,2017-01-07 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,16.83,0,16.83
...,...,...,...,...,...,...,...,...,...,...,...
609,610,55,2020-12-21 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,6.93,0,6.93
610,611,52,2020-12-27 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,1.98,0,1.98
611,612,33,2020-12-27 00:00:00,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,11.88,0,11.88
612,613,20,2020-12-29 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,8.91,0,8.91
613,614,53,2020-12-30 00:00:00,113 Lupus St,London,None,United Kingdom,SW1V 3EN,12.87,0,12.87

In [7]:
# in this table invoice_id is primary key(unique record)
query='''
select * from invoice where invoice_id=1
'''
sql_query(query)

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total,tax,subtotal
0,1,18,2017-01-03 00:00:00,627 Broadway,New York,NY,USA,10012-2612,15.84,0,15.84

In [8]:
# work on table according to png of erd daigram(schema)
# in this table invoice_id is foreign key
query='''
select * from invoice_line where invoice_id==1
'''
sql_query(query)

    invoice_line_id  invoice_id  track_id  unit_price  quantity
0                 1           1      1158        0.99         1
1                 2           1      1159        0.99         1
2                 3           1      1160        0.99         1
3                 4           1      1161        0.99         1
4                 5           1      1162        0.99         1
5                 6           1      1163        0.99         1
6                 7           1      1164        0.99         1
7                 8           1      1165        0.99         1
8                 9           1      1166        0.99         1
9                10           1      1167        0.99         1
10               11           1      1168        0.99         1
11               12           1      1169        0.99         1
12               13           1      1170        0.99         1
13               14           1      1171        0.99         1
14               15           1      1172        0.99         1
15               16           1      1173        0.99         1

In [9]:
query='''
select * from track where track_id==1158
'''
sql_query(query)

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
0,1158,Right Next Door to Hell,91,2,1,None,182321,3175950,0.99

In [10]:
query = """
    PRAGMA table_info(track)
"""
sql_query(query)
# track_id is (pk)

   cid           name           type  notnull dflt_value  pk
0    0       track_id        INTEGER        1       None   1
1    1           name  NVARCHAR(200)        1       None   0
2    2       album_id        INTEGER        0       None   0
3    3  media_type_id        INTEGER        1       None   0
4    4       genre_id        INTEGER        0       None   0
5    5       composer  NVARCHAR(220)        0       None   0
6    6   milliseconds        INTEGER        1       None   0
7    7          bytes        INTEGER        0       None   0
8    8     unit_price  NUMERIC(10,2)        1       None   0

In [11]:
#invoice_id ,track_id ,track_name, media type name ,quantity & unit price where invoice_id==1
query='''
select il.invoice_id,t.track_id,t.name track_name,m.name media_name,il.quantity,il.unit_price
from invoice_line il 
inner join track t
on
il.track_id=t.track_id
inner join media_type m
on
t.media_type_id=m.media_type_id
where il.invoice_id == 1
'''
sql_query(query)

,invoice_id,track_id,track_name,media_name,quantity,unit_price
0,1,1158,Right Next Door to Hell,Protected AAC audio file,1,0.99
1,1,1159,Dust N' Bones,Protected AAC audio file,1,0.99
2,1,1160,Live and Let Die,Protected AAC audio file,1,0.99
3,1,1161,Don't Cry (Original),Protected AAC audio file,1,0.99
4,1,1162,Perfect Crime,Protected AAC audio file,1,0.99
5,1,1163,You Ain't the First,Protected AAC audio file,1,0.99
6,1,1164,Bad Obsession,Protected AAC audio file,1,0.99
7,1,1165,Back off Bitch,Protected AAC audio file,1,0.99
8,1,1166,Double Talkin' Jive,Protected AAC audio file,1,0.99
9,1,1167,November Rain,Protected AAC audio file,1,0.99
10,1,1168,The Garden,Protected AAC audio file,1,0.99
11,1,1169,Garden of Eden,Protected AAC audio file,1,0.99
12,1,1170,Don't Damn Me,Protected AAC audio file,1,0.99
13,1,1171,Bad Apples,Protected AAC audio file,1,0.99
14,1,1172,Dead Horse,Protected AAC audio file,1,0.99
15,1,1173,Coma,Protected AAC audio file,1,0.99

In [12]:
#invoice_id ,track_id ,track_name, media type name artist name,,quantity & unit price where invoice_id==1
query='''
select il.invoice_id,t.track_id,t.name track_name,ar.name,m.name media_name,il.quantity,il.unit_price
from invoice_line il 
inner join track t
on
il.track_id=t.track_id
inner join media_type m
on
t.media_type_id=m.media_type_id
inner join album al
on
t.album_id=al.album_id
inner join artist ar
on 
al.artist_id=ar.artist_id

where il.invoice_id == 1
'''
sql_query(query)

,invoice_id,track_id,track_name,name,media_name,quantity,unit_price
0,1,1158,Right Next Door to Hell,Guns N' Roses,Protected AAC audio file,1,0.99
1,1,1159,Dust N' Bones,Guns N' Roses,Protected AAC audio file,1,0.99
2,1,1160,Live and Let Die,Guns N' Roses,Protected AAC audio file,1,0.99
3,1,1161,Don't Cry (Original),Guns N' Roses,Protected AAC audio file,1,0.99
4,1,1162,Perfect Crime,Guns N' Roses,Protected AAC audio file,1,0.99
5,1,1163,You Ain't the First,Guns N' Roses,Protected AAC audio file,1,0.99
6,1,1164,Bad Obsession,Guns N' Roses,Protected AAC audio file,1,0.99
7,1,1165,Back off Bitch,Guns N' Roses,Protected AAC audio file,1,0.99
8,1,1166,Double Talkin' Jive,Guns N' Roses,Protected AAC audio file,1,0.99
9,1,1167,November Rain,Guns N' Roses,Protected AAC audio file,1,0.99
10,1,1168,The Garden,Guns N' Roses,Protected AAC audio file,1,0.99
11,1,1169,Garden of Eden,Guns N' Roses,Protected AAC audio file,1,0.99
12,1,1170,Don't Damn Me,Guns N' Roses,Protected AAC audio file,1,0.99
13,1,1171,Bad Apples,Guns N' Roses,Protected AAC audio file,1,0.99
14,1,1172,Dead Horse,Guns N' Roses,Protected AAC audio file,1,0.99
15,1,1173,Coma,Guns N' Roses,Protected AAC audio file,1,0.99

In [13]:
#track_id,album title,artist name
query='''
select t.track_id,al.title album_title,ar.name artist_name
from track t
inner join album al
on
t.album_id=al.album_id
inner join artist ar
on 
al.artist_id=ar.artist_id

'''
sql_query(query)

,track_id,album_title,artist_name
0,1,For Those About To Rock We Salute You,AC/DC
1,6,For Those About To Rock We Salute You,AC/DC
2,7,For Those About To Rock We Salute You,AC/DC
3,8,For Those About To Rock We Salute You,AC/DC
4,9,For Those About To Rock We Salute You,AC/DC
...,...,...,...
3498,3499,Respighi:Pines of Rome,Eugene Ormandy
3499,3500,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
3500,3501,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
3501,3502,Mozart: Chamber Music,Nash Ensemble
3502,3503,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

In [14]:
# count of track ids ,top 10 no. of track album name and artist name
query='''
select count(il.track_id) No_of_track ,al.title album_name,ar.name artist_name
from invoice_line il
inner join track t
on
il.track_id=t.track_id
inner join album al
on
t.album_id=al.album_id
inner join artist ar
on 
al.artist_id=ar.artist_id
group by 2
order by  1 DESC limit 10
'''
sql_query(query)

   No_of_track                                  album_name       artist_name
0          187                        Are You Experienced?      Jimi Hendrix
1           96                                    Faceless          Godsmack
2           93                                   Mezmerize  System Of A Down
3           90                                    Get Born               JET
4           83                                   The Doors         The Doors
5           80                    The Police Greatest Hits        The Police
6           80                             Greatest Hits I             Queen
7           80                                    Big Ones         Aerosmith
8           78  From The Muddy Banks Of The Wishkah [live]           Nirvana
9           76    My Generation - The Very Best Of The Who           The Who

In [15]:
df=sql_query(query)
df.to_csv("convert_and_save.csv") # here we save any thing in any file extension

In [16]:
query='''
select e.first_name,e.last_name,e.reports_to
from employee e
'''
sql_query(query)

  first_name last_name  reports_to
0     Andrew     Adams         NaN
1      Nancy   Edwards         1.0
2       Jane   Peacock         2.0
3   Margaret      Park         2.0
4      Steve   Johnson         2.0
5    Michael  Mitchell         1.0
6     Robert      King         6.0
7      Laura  Callahan         6.0

In [17]:
# concate first and last name as full name
query='''
select e.first_name ||" " || e.last_name Full_name,e.reports_to
from employee e
'''
sql_query(query)

          Full_name  reports_to
0      Andrew Adams         NaN
1     Nancy Edwards         1.0
2      Jane Peacock         2.0
3     Margaret Park         2.0
4     Steve Johnson         2.0
5  Michael Mitchell         1.0
6       Robert King         6.0
7    Laura Callahan         6.0

In [18]:
query='''
select e1.first_name ||" " || e1.last_name Full_name,e1.title,e1.reports_to,e1.employee_id,e2.first_name ||" " || e2.last_name Supervisor_name
from employee e1
left join employee e2
on
e1.employee_id=e2.reports_to
'''
sql_query(query)
# only this have relation with his own so that why take join on itself

,Full_name,title,reports_to,employee_id,Supervisor_name
0,Andrew Adams,General Manager,NaN,1,Nancy Edwards
1,Andrew Adams,General Manager,NaN,1,Michael Mitchell
2,Nancy Edwards,Sales Manager,1.0,2,Jane Peacock
3,Nancy Edwards,Sales Manager,1.0,2,Margaret Park
4,Nancy Edwards,Sales Manager,1.0,2,Steve Johnson
5,Jane Peacock,Sales Support Agent,2.0,3,None
6,Margaret Park,Sales Support Agent,2.0,4,None
7,Steve Johnson,Sales Support Agent,2.0,5,None
8,Michael Mitchell,IT Manager,1.0,6,Robert King
9,Michael Mitchell,IT Manager,1.0,6,Laura Callahan
10,Robert King,IT Staff,6.0,7,None
11,Laura Callahan,IT Staff,6.0,8,None

In [19]:
query='''
select first_name ||" " || last_name customer_name, phone Contact from customer
where first_name like "%jen%"
'''
sql_query(query)
# % its allow no or more (may be their is no character or maybe many) in this case %jen% before and after jen have no or more character

       customer_name            Contact
0  Jennifer Peterson  +1 (604) 688-2255

In [20]:
query='''
select first_name ||" " || last_name customer_name, phone Contact from customer
where first_name like "_an%"
'''
sql_query(query)
# _ its allow only one character

      customer_name            Contact
0        Dan Miller  +1 (650) 644-3358
1  Hannah Schneider   +49 030 26550280
2      Manoj Pareek  +91 0124 39883988

In [21]:
query='''
select c.first_name ||" " || c.last_name customer_name, count(i.invoice_id) No_of_invoice,sum(i.total) total_Spent from customer c
inner join invoice i
on c.customer_id=i.customer_id
group by c.customer_id
order by 3 DESC limit 5
'''
sql_query(query)
# count and sum

           customer_name  No_of_invoice  total_Spent
0  František Wichterlová             18       144.54
1            Helena Holý             12       128.70
2          Hugh O'Reilly             13       114.84
3           Manoj Pareek             13       111.87
4         Luís Gonçalves             13       108.90

In [22]:
query='''
select c.*, i.invoice_id
from customer c
inner join invoice i
on c.customer_id=i.customer_id
group by c.customer_id

'''
sql_query(query)
# c* all customer info

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,invoice_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3,16
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5,69
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3,31
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4,24
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,78
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5,112
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5,123
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4,97
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4,21
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4,19
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5,135
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3,28
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4,73
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5,132
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3,60
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4,66
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5,98
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3,1
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3,42
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4,17
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5,44
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4,43
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4,139
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3,18
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5,14
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4,54
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4,5
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5,118
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3,120
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3,2
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5,6
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4,92
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3,34
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4,35
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4,13
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5,45
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3,40
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3,11
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4,25
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4,3
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5,160
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3,12
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3,20
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3,15
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3,29
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3,30
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5,65
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5,84
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4,7
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5,41
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5,36
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3,64
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3,23
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5,106
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4,26
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4,218
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5,47
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3,33
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3,8

In [23]:
query='''
select c.first_name ||" " || c.last_name customer_name, count(i.invoice_id) No_of_invoice,sum(i.total) total_Spent,
Case
    when sum(i.total)< 40 then "Small Spender"
    when sum(i.total)> 100 then "Big Spender"
    else "Normal Spender"
End as spender_category
from customer c
inner join invoice i
on c.customer_id=i.customer_id
group by c.customer_id
order by 3 DESC 
'''
sql_query(query)
# case for condition

            customer_name  No_of_invoice  total_Spent spender_category
0   František Wichterlová             18       144.54      Big Spender
1             Helena Holý             12       128.70      Big Spender
2           Hugh O'Reilly             13       114.84      Big Spender
3            Manoj Pareek             13       111.87      Big Spender
4          Luís Gonçalves             13       108.90      Big Spender
5          Fernanda Ramos             15       106.92      Big Spender
6          João Fernandes             13       102.96      Big Spender
7       François Tremblay              9        99.99   Normal Spender
8            Wyatt Girard             11        99.99   Normal Spender
9              Jack Smith             12        98.01   Normal Spender
10          Enrique Muñoz             11        98.01   Normal Spender
11            Phil Hughes             11        98.01   Normal Spender
12             Luis Rojas             13        97.02   Normal Spender
13             Dan Miller             12        95.04   Normal Spender
14        Fynn Zimmermann             10        94.05   Normal Spender
15        Heather Leacock             12        92.07   Normal Spender
16            Kathy Chase             11        91.08   Normal Spender
17         Edward Francis             13        91.08   Normal Spender
18     Richard Cunningham             12        86.13   Normal Spender
19       Hannah Schneider             11        85.14   Normal Spender
20           Patrick Gray              9        84.15   Normal Spender
21          Leonie Köhler             11        82.17   Normal Spender
22        Roberto Almeida             11        82.17   Normal Spender
23       Madalena Sampaio             16        82.17   Normal Spender
24            Mark Taylor             10        81.18   Normal Spender
25        Michelle Brooks              8        79.20   Normal Spender
26        Camille Bernard              9        79.20   Normal Spender
27       Terhi Hämäläinen             11        79.20   Normal Spender
28           Steve Murray              9        79.20   Normal Spender
29        Ladislav Kovács             10        78.21   Normal Spender
30         Victor Stevens             10        76.23   Normal Spender
31       Stanisław Wójcik             10        76.23   Normal Spender
32         Ellie Sullivan             12        75.24   Normal Spender
33       Joakim Johansson             10        75.24   Normal Spender
34           Frank Harris              8        74.25   Normal Spender
35        Niklas Schröder              9        73.26   Normal Spender
36       Isabelle Mercier             12        73.26   Normal Spender
37           Bjørn Hansen              9        72.27   Normal Spender
38          Julia Barnett             10        72.27   Normal Spender
39     Dominique Lefebvre              9        72.27   Normal Spender
40          Frank Ralston              8        71.28   Normal Spender
41        Puja Srivastava              8        71.28   Normal Spender
42         Aaron Mitchell              8        70.29   Normal Spender
43          Astrid Gruber              9        69.30   Normal Spender
44        Alexandre Rocha             10        69.30   Normal Spender
45             Emma Jones              8        68.31   Normal Spender
46      Jennifer Peterson              9        66.33   Normal Spender
47            John Gordon             10        66.33   Normal Spender
48  Johannes Van der Berg             10        65.34   Normal Spender
49            Marc Dubois              9        64.35   Normal Spender
50            Martha Silk             11        62.37   Normal Spender
51           Daan Peeters              7        60.39   Normal Spender
52        Eduardo Martins             12        60.39   Normal Spender
53              Tim Goyer              9        54.45   Normal Spender
54          Lucas Mancini              9        50.49   Normal Spender
55           Robert Brown              4        40.59   Normal Spender
56        Diego Gutiérrez              5        39.60    Small Spender
57           Kara Nielsen             10        37.62    Small Spender
58           Mark Philips             10        29.70    Small Spender

In [31]:
# value_count 
q = '''SELECT first_name || ' ' || last_name Customer_Name, 
        count(inv.invoice_id) No_Of_Invoices,
        sum(total) Total_Spent,
        Case
            when sum(inv.total) < 40 then "Small Spender"
            when sum(inv.total) > 100 then "Big Spender"
            Else "Regular"
        End as Customer_category
        from customer c
        inner join invoice inv
        on 
        c.customer_id = inv.customer_id
        group by c.customer_id
        order by 1
        
'''
sql_query(q)["Customer_category"].value_counts()

Customer_category
Regular          49
Big Spender       7
Small Spender     3
Name: count, dtype: int64

In [32]:
q = """select c.*, sum(inv.total) Total_Spent
        from customer c
        left join invoice inv
        on
        c.customer_id = inv.customer_id
        group by c.customer_id
        having Total_Spent > 90

"""#different between having and where are having write with condition or clause
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,Total_Spent
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3,108.90
1,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3,99.99
2,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,144.54
3,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5,128.70
4,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4,106.92
5,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5,98.01
6,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4,95.04
7,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5,91.08
8,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4,92.07
9,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3,91.08
10,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4,102.96
11,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3,94.05
12,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3,99.99
13,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3,114.84
14,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5,98.01
15,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3,98.01
16,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5,97.02
17,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3,111.87

In [33]:
# customer all col , Top 3 total invoice
q = """select c.*, sum(inv.total) Total_Spent
        from customer c
        left join invoice inv
        on
        c.customer_id = inv.customer_id
        group by c.customer_id
        having Total_Spent > 90
        order by Total_Spent DESC limit 3
        

"""
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,Total_Spent
0,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,144.54
1,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5,128.70
2,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3,114.84

In [34]:
# track_id, total_sale

q = """SELECT t.track_id, sum(il.quantity) Total_Sale FROM track t
        left JOIN invoice_line il
        ON
        t.track_id = il.track_id
        GROUP BY 1
        """

sql_query(q)

      track_id  Total_Sale
0            1         8.0
1            2         3.0
2            3         1.0
3            4         4.0
4            5         1.0
...        ...         ...
3498      3499         NaN
3499      3500         2.0
3500      3501         NaN
3501      3502         NaN
3502      3503         NaN

[3503 rows x 2 columns]

In [24]:
# create Table
q='''
create table Spender as
select c.first_name ||" " || c.last_name customer_name, count(i.invoice_id) No_of_invoice,sum(i.total) total_Spent,
Case
    when sum(i.total)< 40 then "Small Spender"
    when sum(i.total)> 100 then "Big Spender"
    else "Normal Spender"
End as spender_category
from customer c
inner join invoice i
on c.customer_id=i.customer_id
group by c.customer_id
order by 3 DESC 
'''
conn.execute(q)# save

In [25]:
pd.read_sql_query("select * from sqlite_master",con=conn)

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,index,sqlite_autoindex_playlist_track_1,playlist_track,12,None
11,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
12,index,ifk_albumartist_id,album,16,CREATE INDEX [ifk_albumartist_id] ON [album] (...
13,index,ifk_customersupport_rep_id,customer,17,CREATE INDEX [ifk_customersupport_rep_id] ON [...
14,index,ifk_employeereports_to,employee,18,CREATE INDEX [ifk_employeereports_to] ON [empl...
15,index,ifk_invoicecustomer_id,invoice,19,CREATE INDEX [ifk_invoicecustomer_id] ON [invo...
16,index,ifk_invoice_lineinvoice_id,invoice_line,20,CREATE INDEX [ifk_invoice_lineinvoice_id] ON [...
17,index,ifk_invoice_linetrack_id,invoice_line,21,CREATE INDEX [ifk_invoice_linetrack_id] ON [in...
18,index,ifk_playlist_tracktrack_id,playlist_track,22,CREATE INDEX [ifk_playlist_tracktrack_id] ON [...
19,index,ifk_trackalbum_id,track,23,CREATE INDEX [ifk_trackalbum_id] ON [track] ([...
20,index,ifk_trackgenre_id,track,24,CREATE INDEX [ifk_trackgenre_id] ON [track] ([...
21,index,ifk_trackmedia_type_id,track,25,CREATE INDEX [ifk_trackmedia_type_id] ON [trac...
22,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
23,index,sqlite_autoindex_wishlist_track_1,wishlist_track,262,None
24,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
25,view,CUSTOMER_ABV2_90,CUSTOMER_ABV2_90,0,CREATE VIEW CUSTOMER_ABV2_90 as \n sele...
26,view,customer_get_90_dollars,customer_get_90_dollars,0,CREATE VIEW customer_get_90_dollars as\n Sel...
27,view,customer_usa,customer_usa,0,CREATE VIEW customer_usa as\n sele...
28,view,customer_gt_90_dollars,customer_gt_90_dollars,0,CREATE VIEW customer_gt_90_dollars as\n Sele...
29,view,city_redmond,city_redmond,0,CREATE VIEW city_redmond as\n sele...
30,view,CUSTOMER_ABV3_80,CUSTOMER_ABV3_80,0,CREATE VIEW CUSTOMER_ABV3_80 as \n sele...
31,table,Spender,Spender,266,"CREATE TABLE Spender(\n customer_name,\n No_..."

In [26]:
# see spender table create

In [27]:
q="select * from Spender"
sql_query(q)

            customer_name  No_of_invoice  total_Spent spender_category
0   František Wichterlová             18       144.54      Big Spender
1             Helena Holý             12       128.70      Big Spender
2           Hugh O'Reilly             13       114.84      Big Spender
3            Manoj Pareek             13       111.87      Big Spender
4          Luís Gonçalves             13       108.90      Big Spender
5          Fernanda Ramos             15       106.92      Big Spender
6          João Fernandes             13       102.96      Big Spender
7       François Tremblay              9        99.99   Normal Spender
8            Wyatt Girard             11        99.99   Normal Spender
9              Jack Smith             12        98.01   Normal Spender
10          Enrique Muñoz             11        98.01   Normal Spender
11            Phil Hughes             11        98.01   Normal Spender
12             Luis Rojas             13        97.02   Normal Spender
13             Dan Miller             12        95.04   Normal Spender
14        Fynn Zimmermann             10        94.05   Normal Spender
15        Heather Leacock             12        92.07   Normal Spender
16            Kathy Chase             11        91.08   Normal Spender
17         Edward Francis             13        91.08   Normal Spender
18     Richard Cunningham             12        86.13   Normal Spender
19       Hannah Schneider             11        85.14   Normal Spender
20           Patrick Gray              9        84.15   Normal Spender
21          Leonie Köhler             11        82.17   Normal Spender
22        Roberto Almeida             11        82.17   Normal Spender
23       Madalena Sampaio             16        82.17   Normal Spender
24            Mark Taylor             10        81.18   Normal Spender
25        Michelle Brooks              8        79.20   Normal Spender
26        Camille Bernard              9        79.20   Normal Spender
27       Terhi Hämäläinen             11        79.20   Normal Spender
28           Steve Murray              9        79.20   Normal Spender
29        Ladislav Kovács             10        78.21   Normal Spender
30         Victor Stevens             10        76.23   Normal Spender
31       Stanisław Wójcik             10        76.23   Normal Spender
32         Ellie Sullivan             12        75.24   Normal Spender
33       Joakim Johansson             10        75.24   Normal Spender
34           Frank Harris              8        74.25   Normal Spender
35        Niklas Schröder              9        73.26   Normal Spender
36       Isabelle Mercier             12        73.26   Normal Spender
37           Bjørn Hansen              9        72.27   Normal Spender
38          Julia Barnett             10        72.27   Normal Spender
39     Dominique Lefebvre              9        72.27   Normal Spender
40          Frank Ralston              8        71.28   Normal Spender
41        Puja Srivastava              8        71.28   Normal Spender
42         Aaron Mitchell              8        70.29   Normal Spender
43          Astrid Gruber              9        69.30   Normal Spender
44        Alexandre Rocha             10        69.30   Normal Spender
45             Emma Jones              8        68.31   Normal Spender
46      Jennifer Peterson              9        66.33   Normal Spender
47            John Gordon             10        66.33   Normal Spender
48  Johannes Van der Berg             10        65.34   Normal Spender
49            Marc Dubois              9        64.35   Normal Spender
50            Martha Silk             11        62.37   Normal Spender
51           Daan Peeters              7        60.39   Normal Spender
52        Eduardo Martins             12        60.39   Normal Spender
53              Tim Goyer              9        54.45   Normal Spender
54          Lucas Mancini              9        50.49   Normal Spender
55           Robert Brown              4        40.59   Normal Spender
56        Diego Gutiérrez              5        39.60    Small Spender
57           Kara Nielsen             10        37.62    Small Spender
58           Mark Philips             10        29.70    Small Spender

In [28]:
conn.execute("Drop table Spender")

In [29]:
pd.read_sql_query("select * from sqlite_master",con=conn)

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,index,sqlite_autoindex_playlist_track_1,playlist_track,12,None
11,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
12,index,ifk_albumartist_id,album,16,CREATE INDEX [ifk_albumartist_id] ON [album] (...
13,index,ifk_customersupport_rep_id,customer,17,CREATE INDEX [ifk_customersupport_rep_id] ON [...
14,index,ifk_employeereports_to,employee,18,CREATE INDEX [ifk_employeereports_to] ON [empl...
15,index,ifk_invoicecustomer_id,invoice,19,CREATE INDEX [ifk_invoicecustomer_id] ON [invo...
16,index,ifk_invoice_lineinvoice_id,invoice_line,20,CREATE INDEX [ifk_invoice_lineinvoice_id] ON [...
17,index,ifk_invoice_linetrack_id,invoice_line,21,CREATE INDEX [ifk_invoice_linetrack_id] ON [in...
18,index,ifk_playlist_tracktrack_id,playlist_track,22,CREATE INDEX [ifk_playlist_tracktrack_id] ON [...
19,index,ifk_trackalbum_id,track,23,CREATE INDEX [ifk_trackalbum_id] ON [track] ([...
20,index,ifk_trackgenre_id,track,24,CREATE INDEX [ifk_trackgenre_id] ON [track] ([...
21,index,ifk_trackmedia_type_id,track,25,CREATE INDEX [ifk_trackmedia_type_id] ON [trac...
22,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
23,index,sqlite_autoindex_wishlist_track_1,wishlist_track,262,None
24,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
25,view,CUSTOMER_ABV2_90,CUSTOMER_ABV2_90,0,CREATE VIEW CUSTOMER_ABV2_90 as \n sele...
26,view,customer_get_90_dollars,customer_get_90_dollars,0,CREATE VIEW customer_get_90_dollars as\n Sel...
27,view,customer_usa,customer_usa,0,CREATE VIEW customer_usa as\n sele...
28,view,customer_gt_90_dollars,customer_gt_90_dollars,0,CREATE VIEW customer_gt_90_dollars as\n Sele...
29,view,city_redmond,city_redmond,0,CREATE VIEW city_redmond as\n sele...
30,view,CUSTOMER_ABV3_80,CUSTOMER_ABV3_80,0,CREATE VIEW CUSTOMER_ABV3_80 as \n sele...

In [30]:
# see delete (drop)

In [35]:
# After three letter 'en' would be match because given ___ so that's why

q = """SELECT first_name || " " || last_name Customer_Name, Phone FROM customer
        WHERE first_name LIKE '___en%'
        group by 1"""

sql_query(q)

  Customer_Name             phone
0   Helena Holý  +420 2 4177 0449

In [36]:
# Another Example
q = """SELECT first_name || " " || last_name Customer_Name, Phone FROM customer
        WHERE first_name LIKE '___an%'
        group by 1"""

sql_query(q)

           Customer_Name            phone
0  Johannes Van der Berg  +31 020 6223130

In [37]:
q = """SELECT first_name || " " || last_name Customer_Name, Phone FROM customer
        WHERE first_name LIKE '_e_ni_er' """

sql_query(q)

       Customer_Name              phone
0  Jennifer Peterson  +1 (604) 688-2255

In [38]:
q = """select c.customer_id, c.first_name ||" "|| c.last_name full_name, c.country,
       sum(i.total) Total_purchased
       from customer c
       inner join invoice i 
       on
       c.customer_id = i.customer_id
       group by 1"""
sql_query(q)

    customer_id              full_name         country  Total_purchased
0             1         Luís Gonçalves          Brazil           108.90
1             2          Leonie Köhler         Germany            82.17
2             3      François Tremblay          Canada            99.99
3             4           Bjørn Hansen          Norway            72.27
4             5  František Wichterlová  Czech Republic           144.54
5             6            Helena Holý  Czech Republic           128.70
6             7          Astrid Gruber         Austria            69.30
7             8           Daan Peeters         Belgium            60.39
8             9           Kara Nielsen         Denmark            37.62
9            10        Eduardo Martins          Brazil            60.39
10           11        Alexandre Rocha          Brazil            69.30
11           12        Roberto Almeida          Brazil            82.17
12           13         Fernanda Ramos          Brazil           106.92
13           14           Mark Philips          Canada            29.70
14           15      Jennifer Peterson          Canada            66.33
15           16           Frank Harris             USA            74.25
16           17             Jack Smith             USA            98.01
17           18        Michelle Brooks             USA            79.20
18           19              Tim Goyer             USA            54.45
19           20             Dan Miller             USA            95.04
20           21            Kathy Chase             USA            91.08
21           22        Heather Leacock             USA            92.07
22           23            John Gordon             USA            66.33
23           24          Frank Ralston             USA            71.28
24           25         Victor Stevens             USA            76.23
25           26     Richard Cunningham             USA            86.13
26           27           Patrick Gray             USA            84.15
27           28          Julia Barnett             USA            72.27
28           29           Robert Brown          Canada            40.59
29           30         Edward Francis          Canada            91.08
30           31            Martha Silk          Canada            62.37
31           32         Aaron Mitchell          Canada            70.29
32           33         Ellie Sullivan          Canada            75.24
33           34         João Fernandes        Portugal           102.96
34           35       Madalena Sampaio        Portugal            82.17
35           36       Hannah Schneider         Germany            85.14
36           37        Fynn Zimmermann         Germany            94.05
37           38        Niklas Schröder         Germany            73.26
38           39        Camille Bernard          France            79.20
39           40     Dominique Lefebvre          France            72.27
40           41            Marc Dubois          France            64.35
41           42           Wyatt Girard          France            99.99
42           43       Isabelle Mercier          France            73.26
43           44       Terhi Hämäläinen         Finland            79.20
44           45        Ladislav Kovács         Hungary            78.21
45           46          Hugh O'Reilly         Ireland           114.84
46           47          Lucas Mancini           Italy            50.49
47           48  Johannes Van der Berg     Netherlands            65.34
48           49       Stanisław Wójcik          Poland            76.23
49           50          Enrique Muñoz           Spain            98.01
50           51       Joakim Johansson          Sweden            75.24
51           52             Emma Jones  United Kingdom            68.31
52           53            Phil Hughes  United Kingdom            98.01
53           54           Steve Murray  United Kingdom            79.20
54           55            Mark Taylor       Australia            81.18
55           56        Diego Gutiérrez       Argentina            39.60
56           57             Luis Rojas           Chile            97.02
57           58           Manoj Pareek           India           111.87
58           59        Puja Srivastava           India            71.28

In [39]:
#  customer from each country that has spent the most money at our store
# Best customer_id, Customer_name, Country, Top_Buyer

q = """with best_customer_id as
       (select c.customer_id, c.first_name ||" "|| c.last_name full_name, c.country,
       sum(i.total) Total_purchased
       from customer c
       inner join invoice i 
       on
       c.customer_id = i.customer_id
       group by 1)
       
       
       select customer_id, country, full_name, max(Total_purchased) Top_buyer
       from best_customer_id
       group by 2

    """
# here we use sub query cause we have to use sum and max at same time which is not possible so we use 
# sub query like make (with best_customer_id) then take sum(i.total) then select from best_customer_id and take max(total_purchased)
sql_query(q)

    customer_id         country              full_name  Top_buyer
0            56       Argentina        Diego Gutiérrez      39.60
1            55       Australia            Mark Taylor      81.18
2             7         Austria          Astrid Gruber      69.30
3             8         Belgium           Daan Peeters      60.39
4             1          Brazil         Luís Gonçalves     108.90
5             3          Canada      François Tremblay      99.99
6            57           Chile             Luis Rojas      97.02
7             5  Czech Republic  František Wichterlová     144.54
8             9         Denmark           Kara Nielsen      37.62
9            44         Finland       Terhi Hämäläinen      79.20
10           42          France           Wyatt Girard      99.99
11           37         Germany        Fynn Zimmermann      94.05
12           45         Hungary        Ladislav Kovács      78.21
13           58           India           Manoj Pareek     111.87
14           46         Ireland          Hugh O'Reilly     114.84
15           47           Italy          Lucas Mancini      50.49
16           48     Netherlands  Johannes Van der Berg      65.34
17            4          Norway           Bjørn Hansen      72.27
18           49          Poland       Stanisław Wójcik      76.23
19           34        Portugal         João Fernandes     102.96
20           50           Spain          Enrique Muñoz      98.01
21           51          Sweden       Joakim Johansson      75.24
22           17             USA             Jack Smith      98.01
23           53  United Kingdom            Phil Hughes      98.01